# Generated by Django 6.0.1 on 2026-01-29 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_main_images_product_main_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='main_image',
            new_name='main_images',
        ),
    ]
