# Generated by Django 6.0.1 on 2026-01-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_main_images_product_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_image',
        ),
        migrations.AddField(
            model_name='product',
            name='main_images',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
