# Generated by Django 6.0.1 on 2026-01-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_main_image_product_main_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_images',
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/main/'),
        ),
    ]
